import { normalizeDocCode } from './lifecycleWorkflows.js';

/** Roles allowed to generate exit / settlement letters */
export const HR_LIFECYCLE_ROLES = new Set([
  'admin',
  'SUPER_ADMIN',
  'shop_owner',
  'HR_MANAGER',
  'HR_EXECUTIVE',
]);

export const EXIT_DOCUMENT_CODES = new Set([
  'RESIGNATION_ACCEPTANCE',
  'NO_DUES_CLEARANCE',
  'FULL_FINAL_STATEMENT',
  'RELIEVING_LETTER',
]);

export function isExitDocumentCode(code) {
  return EXIT_DOCUMENT_CODES.has(normalizeDocCode(code));
}

export function canGenerateLifecycleDocument(user, docCode) {
  const code = normalizeDocCode(docCode);
  if (!isExitDocumentCode(code)) return { allowed: true };

  const role = user?.role || '';
  if (HR_LIFECYCLE_ROLES.has(role)) return { allowed: true };

  return {
    allowed: false,
    message:
      'Exit and settlement letters can only be generated by HR (HR Manager / HR Executive) or administrators.',
  };
}
